name: spioc_portfolio
description: "Simone Pio's portofolio website"
publish_to: 'none'
version: 1.4.6

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.6
  url_launcher: ^6.3.0
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  responsive_builder: ^0.7.1
  gap: ^3.0.1
  transparent_image: ^2.0.1
  simple_icons: ^10.1.3
  confetti: ^0.8.0
  flutter_markdown: ^0.7.3+1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/pdfs/

  fonts:
    - family: Bebas Neue
      fonts:
        - asset: fonts/bebas_neue/BebasNeue-Regular.ttf
          weight: 400
    - family: Fira Sans Condensed
      fonts:
        - asset: fonts/fira_sans_condensed/FiraSansCondensed-Regular.ttf
          weight: 400
        - asset: fonts/fira_sans_condensed/FiraSansCondensed-SemiBold.ttf
          weight: 600
        - asset: fonts/fira_sans_condensed/FiraSansCondensed-Bold.ttf
          weight: 700

scripts:
  clean_and_get:
    - flutter clean && flutter pub get
  build_web:
    - flutter build web
  generate_web_release:
    - $clean_and_get
    - $build_web --release --wasm